### PR TITLE
Refactor reading of migration BIN.JSON file to use JsonConfigurable

### PR DESCRIPTION
**Pull request by Bridenbecker**
- Changed the code that read the migration metadata so that it uses the standard JsonConfigurable code.
- Should not change any behavior except maybe error messages

### CODE REVIEW

**Comment by stitova-idm** [comment]
image
I'm getting this error because the file does not have any MigrationType defined. We do not need migration Types for vector migration. We should just ignore them if they are present.

**Comment by stitova-idm** [comment]
We should not be showing this for VectorMigration. There's no MigrationType and there's no Interpolation as far as the user is concerned. Also the default internal InterpolationType is PIECEWISE_CONSTANT for Vector Migration
00:00:00 [0] [D] [JsonConfigurable] Using the default value ( "MigrationType" : "NO_MIGRATION" ) for unspecified parameter.
00:00:00 [0] [D] [JsonConfigurable] Using the default value ( "InterpolationType" : "LINEAR_INTERPOLATION" ) for unspecified parameter.   <--- I feel like this would be confusing 'cause I'd be worried that stuff is getting interpolated and that vectors are not migrating correctly even when they are

**Comment by stitova-idm** [comment]
Does not say anything when MigrationType != VECTOR_MIGRATION_BY_GENETICS, but Allele_Combinations is present. Just gives you the generic "unexpected filesize data" error. Would be nice if it said something.

**Comment by stitova-idm** [comment]
General: maybe we can expand the "I/O error while reading/writing. File name =  c:/EMOD/input_data/MigrationTest/9_nodes_by_alleles.bin.  Detected wrong size for migration data file.  Expected 96 bytes, read 480 bytes"  with "Expected Data size is calculated by using MigrationType and AgesYears (or Allele_Combinations for vector migration) settings. Please make sure those are set correctly."

**Comment by stitova-idm** [comment]
GeneralConfigurationException: 
Exception in utils\Configure.h at 733 in Kernel::JsonConfigurable::initConfig.
Failed to find enum match for value 'VECTOR_MIGRAT.ION_BY_GENETICS' and key 'GenderDataType'.
Possible values are:
SAME_FOR_BOTH_GENDERS
ONE_FOR_EACH_GENDER
VECTOR_MIGRATION_BY_GENETICS
Shows up under Human Migration File checking, but VECTOR_MIGRATION_BY_GENETICS is not actually valid for humans (errors out correctly)

**Comment by Bridenbecker** [comment]
> Does not say anything when GenderDataType != VECTOR_MIGRATION_BY_GENETICS, but Allele_Combinations is present. Just gives you the generic "unexpected filesize data" error. Would be nice if it said something.

But this is the way everything works in EMOD.  If you put Trigger_Condition_List just anywhere in your campaign (like I've seen users to recently), we don't say anything.  We just ignore it.

**Comment by Bridenbecker** [comment]
> GeneralConfigurationException: Exception in utils\Configure.h at 733 in Kernel::JsonConfigurable::initConfig. Failed to find enum match for value 'VECTOR_MIGRAT.ION_BY_GENETICS' and key 'GenderDataType'. Possible values are: SAME_FOR_BOTH_GENDERS ONE_FOR_EACH_GENDER VECTOR_MIGRATION_BY_GENETICS Shows up under Human Migration File checking, but VECTOR_MIGRATION_BY_GENETICS is not actually valid for humans (errors out correctly)

yeah. This is annoying, but this is not the only place this occurs.  We would need a new solution.

**Comment by Bridenbecker** [comment]
> General: maybe we can expand the "I/O error while reading/writing. File name = c:/EMOD/input_data/MigrationTest/9_nodes_by_alleles.bin. Detected wrong size for migration data file. Expected 96 bytes, read 480 bytes" with "Expected Data size is calculated by using MigrationType and AgesYears (or Allele_Combinations for vector migration) settings. Please make sure those are set correctly."

Does that really help?  It doesn't tell you the details.

**Pull request merged**
